image:
  file: .gitpod.Dockerfile

tasks:
  - init: >
      docker-compose up -d &&
      composer install &&
      echo "Waiting for MySQL to be ready..." &&
      sleep 15 &&
      php artisan migrate --seed