version: "3.7"
services:
  mysql:
    image: mysql:8
    container_name: mysql-dev
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sendportal_dev
      MYSQL_USER: sendportal
      MYSQL_PASSWORD: sendportal
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: